CREATE TABLE CRM.CUSTOMER_FINANCE_CLEAN AS
SELECT
  client_id,
  TO_NUMBER(REPLACE(REPLACE(per_capita_income, '$',''), ',','')) AS per_capita_income,
  TO_NUMBER(REPLACE(REPLACE(yearly_income, '$',''), ',',''))     AS yearly_income,
  TO_NUMBER(REPLACE(REPLACE(total_debt, '$',''), ',',''))        AS total_debt,
  credit_score,
  num_credit_cards
FROM CRM.CUSTOMER_FINANCE;

--AM FACUT CREATE TABLE CUSTOMER FINANCE AS ..CLEAN SI AM DAT DROP LA TABELA CLEAN

ALTER TABLE CRM.CUSTOMERS
  ADD CONSTRAINT PK_CUSTOMERS PRIMARY KEY (client_id);

ALTER TABLE CRM.CUSTOMER_FINANCE
  ADD CONSTRAINT PK_CUSTOMERS_FIN PRIMARY KEY (client_id);

ALTER TABLE CRM.CUSTOMER_FINANCE
  ADD CONSTRAINT FK_FIN_CUSTOMER
  FOREIGN KEY (client_id) REFERENCES CRM.CUSTOMERS(client_id);
  
GRANT SELECT ON CRM.CUSTOMERS TO FDBO;
GRANT SELECT ON CRM.CUSTOMER_FINANCE TO FDBO;