SHOW CON_NAME;

-- creează user (dacă nu există)
CREATE USER CRM IDENTIFIED BY crm
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO CRM;