server.port=9990
server.servlet.context-path=/DSA-SparkSQL-Service
server.servlet.session.persistent=false

# logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# SpringBoot Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.security.user.name=spark
spring.security.user.password=sql

### SparkSQL REST SQL API
sparksql.rest.enabled=true

### Auto REST mode for SparkSQL views
### Values:
### off        = /rest/view endpoints disabled
### on         = all SparkSQL views can be exposed by name
### restricted = only views with TBLPROPERTIES('AUTOREST') are exposed
sparksql.autorest.mode=on
