server.port=9080
server.servlet.context-path=/DSA-WEB-VaadinService

spring.application.name=DSA-WEB-VaadinService

logging.level.org.atmosphere=warn

dsa.backend.base-url=http://localhost:8096/DSA-WEB-RESTService/rest/OLAP

vaadin.launch-browser=true